### ISSUE TITLE
exit_fee calculation is incorrect

### ISSUE THREAD

**Issue by thibauld** [Fairmint/c-org#248]
The `exit_fee` calculus should be:
`exit_fee=total_supply*(total_supply+burnt_supply)*buy_slope - buyback_reserve`

This formula has been confirmed by Blockscience to be correct:
![image](https://user-images.githubusercontent.com/197119/66242240-30089b80-e6cf-11e9-921a-f4b257b390ad.png)

**Comment by thibauld** [comment]
Spec has been updated accordingly: https://github.com/Fairmint/c-org/wiki/Home/_compare/48beeca2b947a7729c1d02e243cdb55c94ce18ca...664bd8403235bd36f144803b1f00eeac17c773ac

**Comment by NickCuso** [comment]
@thibauld this change breaks most the csv tests
