### ISSUE TITLE
Implement of the c-org smart-contracts in Vyper

### ISSUE THREAD

**Issue by thibauld** [Fairmint/c-org#3]
Based on the specification written in this repository's wiki, implement a first fully functional version of the c-org smart-contracts using the Vyper language. Given the highly sensitive nature of the c-org contracts (holding potentially very large amount of value), using Vyper over Solidity seems like the right path to take. Especially since Uniswap proved it was a [totally viable option](https://github.com/Uniswap/contracts-vyper).

**Comment by thibauld** [comment]
The specification of the c-org smart-contract is available here:
https://github.com/Fairmint/c-org/wiki

**Comment by NickCuso** [comment]
Implementation complete and now in testing.
